image: python:3.8-slim

pages:
  script:
  - pip install -r docs/requirements.txt
  - sphinx-build -c docs -d _build/doctrees . docs/_build/html
  - cp _build/html public
  artifacts:
    paths:
    - public
  only:
  - main
